### ISSUE TITLE
User doesn't get descriptive error messages

### ISSUE THREAD

**Issue by Walther** [WePaHT-SQL/SQLTasker#35]
In case of syntax errors, the checker might return something completely unrelated, e.g. `Query should have table OPISKELIJA`.

Expected behavior: proper error message pointing out the possible syntax error and its location.

**Comment by ArktinenSieni** [comment]
The error message was task-related. The task used a database where such table existed. However, if sent query is not valid, it fails to create the database. In this case program then compares empty table with a correct table resulting this confusing error message. 

In that task, empty database is now set, and it gives more proper message.
Not having descriptive errors is still a problem in SQLTasker. 
For further issues, please address them to https://github.com/RAGE/SQLTasker/
